<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIptyftj\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIptyftj/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerIptyftj.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerIptyftj\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerIptyftj\appProdProjectContainer(array(
    'container.build_hash' => 'Iptyftj',
    'container.build_id' => 'ab47efeb',
    'container.build_time' => 1540439548,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerIptyftj');
